export const officesData = [
  {
    category1000: [
      {
        id: "4(А,В,С)-301(Ф)",
        area: "2062,50",
        building: "4",
        purpose: "Офісне приміщення",
        photos: [
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717611487/136_gwrh3p.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717611486/127_ocwwrk.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717611486/132_zqhppf.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717611831/4_%D0%90_%D0%92_%D0%A1_-301_%D0%A4__page-0001_1_hoigit.jpg",
        ],
      },
      {
        id: "4(А,В,С)-601(Ф)",
        area: "2062,94",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "5(А)-201(Б)",
        area: "1868,45",
        building: "5",
        purpose: "Офісне приміщення",
        photos: [
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717612726/IMG_2144_vrm35c.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717612723/IMG_1023_j8qzfw.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717612725/IMG_2147_qvbpxh.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717612876/5_%D0%90_-201_%D0%91__page-0001_dls1wj.jpg",
        ],
      },
      {
        id: "5(А)-301",
        area: "1760,65",
        building: "5",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "5(А)-401(Б)",
        area: "1744,74",
        building: "5",
        purpose: "Офісне приміщення",
        photos: [
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717613200/218_ajfrj5.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717613198/212_rpmati.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717613198/212_rpmati.jpg",
          "https://res.cloudinary.com/dws8qdbjg/image/upload/v1717613358/5_%D0%90_-401_%D0%91_3__page-0001_kftqfa.jpg",
        ],
      },
    ],
  },
  {
    category500: [
      {
        id: "2(D)-305(Р)",
        area: "675,43",
        building: "2",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(А)-202(Ф)",
        area: "805,38",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(А)-402(Ф)",
        area: "932,36",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(А)-502(Ф)",
        area: "841,92",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "5(А)-503/2(Б)",
        area: "523,93",
        building: "5",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category300: [
      {
        id: "2(D)-204(Р)",
        area: "509,80",
        building: "2",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "2(D)-401(Р)",
        area: "464,20",
        building: "2",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(A)-201(Ф)",
        area: "420,31",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(B)-204(Ф)",
        area: "476,30",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(В)-203(Ф)",
        area: "415,69",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category200: [
      {
        id: "2(С)-109(Р)",
        area: "305,80",
        building: "2",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "3(A)-202(Ф)",
        area: "230,45",
        building: "3",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(B)-403(Ф)",
        area: "308,99",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category100: [
      {
        id: "1(А)-201(Х)",
        area: "180,73",
        building: "1",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "2(А,В)-302",
        area: "160,63",
        building: "2",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "3(B)-301(Ф)",
        area: "144,99",
        building: "3",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "3(A)-603(Ф)",
        area: "194,15",
        building: "3",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "3(B)-703(Ф)",
        area: "184,71",
        building: "3",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    categoryLess100: [
      {
        id: "1(В)-101(Х)",
        area: "53,9",
        building: "1",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "1(А)-103/2(Х)",
        area: "26,46",
        building: "1",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "1(В)-102(Х)",
        area: "69,80",
        building: "1",
        purpose: "Громадське харчування, лабораторія, косметологія",
        photos: ["", "", "", ""],
      },
      {
        id: "1(А)-103/7(Х)",
        area: "40,94",
        building: "1",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "6-102(Б)",
        area: "95,76",
        building: "6",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
    ],
  },
];
