export const officesData = [
  {
    category1000: [
      {
        id: "4(А,В,С)-301(Ф)",
        area: "2062,50",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "4(А,В,С)-601(Ф)",
        area: "2062,94",
        building: "4",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "5(А)-201(Б)",
        area: "1868,45",
        building: "5",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "5(А)-301",
        area: "1760,65",
        building: "5",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "5(А)-401(Б)",
        area: "1744,74",
        building: "5",
        purpose: "Офісне приміщення",
        photos: ["", "", "", ""],
      },
      {
        id: "6",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category500: [
      {
        id: "7",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "8",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "9",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "10",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "11",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "12",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category300: [
      {
        id: "13",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "14",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "15",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "16",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "17",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "18",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category200: [
      {
        id: "19",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "20",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "21",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "22",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "23",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "24",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    category100: [
      {
        id: "25",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "26",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "27",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "28",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "29",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "30",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
    ],
  },
  {
    categoryLess100: [
      {
        id: "31",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "32",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "33",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "34",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "35",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
      {
        id: "36",
        area: "",
        building: "",
        purpose: "",
        photos: ["", "", "", ""],
      },
    ],
  },
];
